/* Generated By:JavaCC: Do not edit this line. QueryConstants.java */
package com.evgenltd.lt.component.query;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QueryConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 2;
  /** RegularExpression Id. */
  int TRUE = 3;
  /** RegularExpression Id. */
  int FALSE = 4;
  /** RegularExpression Id. */
  int STRING = 5;
  /** RegularExpression Id. */
  int ATTRIBUTE = 6;
  /** RegularExpression Id. */
  int PHRASE = 7;
  /** RegularExpression Id. */
  int WORD = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "<EOL>",
    "\"true\"",
    "\"false\"",
    "<STRING>",
    "<ATTRIBUTE>",
    "<PHRASE>",
    "<WORD>",
    "\"=\"",
  };

}
